### ISSUE TITLE
Bug report about clown science

### ISSUE THREAD

**Issue by PascalAndrews** [Pezzawinkle/MadClowns#21]
A bug when start game with angel and bob when tech overhaul mode enabled. It shows the bug happened in the angel refining and other mod, but when i delete the MadClown Science, the bug disappeared. thus i think the problem occured in this MadClown Science. No idea where it went wong.

**Comment by PascalAndrews** [comment]
btw, the icon size of water-treatment-5 also goes wrong, it's much bigger than the frame, maybe you could renew the code to the same as the new angel refining code.

**Comment by ArcheCraft** [comment]
The Problem is probably her: https://github.com/Pezzawinkle/MadClowns/blob/master/Clowns-Science/prototypes/buildings/particle-accelerator.lua#L6
It seems to expect there to be a 'cobalt-plate', but without Bobs Plates there is only a 'angels-plate-cobalt'
Also the crash happens only without bobs mods, as Angels then uses its own plate items

**Comment by Pezzawinkle** [comment]
thanks for the catch, that was actually the tip of the spear as it were... ill get an update out shortly with the fixes
