### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by RealTigerCZ** [Pezzawinkle/MadClowns#25]
Hi, I have a problem when loading MadClown's Science mod. I wanted to play [Extreme Multiplayer Modpack](https://mods.factorio.com/mod/multiplayer_extreme_modpack) with my friend and this crash appeared. When I disable this mod, it works normally. Strange is, that it works for my friend (he installed only dependencies not the optional mods). So if needed I can try to find out with what mod it crashes. 

![image](https://user-images.githubusercontent.com/69424769/165335704-f0ce0808-d9ed-477a-a8a2-00fa4d1674ab.png)

Thank you for help :D

**Comment by garrosh** [comment]
Hey, I fixed my local version by changing the file /prototypes/functions.lua at line 137 to:

`log("regular"..tostring(data.raw.recipe[name.."-science-pack"].enabled))`

because the error is about an error concatenating a boolean. Looking it up, lua doesn't automatically typecasts boolean to strings, so you have to cast it manually.

**Comment by Pezzawinkle** [comment]
This is indeed the correct patch, i have this on the git branch already.
