### ISSUE TITLE
Crash with AngelBob Nuclear and Special Vanilla

### ISSUE THREAD

**Issue by KiwiHawk** [Pezzawinkle/MadClowns#43]
![image](https://github.com/Pezzawinkle/MadClowns/assets/59639/cc2e23e0-24ae-4e53-b304-38e4348c25db)

Mod list:
- Angel's Bioprocessing
- Angel's Industries
- Angel's Petrochemical Processing
- Angel's Smelting
- Angel's Refining
- MadClown01's AngelBob Nuclear
- MadClown01's Processing
- MadClown01's Vanilla Nuclear

Angel's Industries Mod settings:
- Industry overhaul: False
- Components overhaul: False
- Technology overhaul: False

**Comment by An1onS** [comment]
Hi!
This crash is fixed by 9e5d667202079ab4ae8d23adc3cdf8d005084f88. Version 1.1.21(2023-07-23) does not include those changes.

Checked Clowns-AngelBob-Nuclear 9e5d667202079ab4ae8d23adc3cdf8d005084f88 with angelsrefining 0.12.5/0.12.6( https://github.com/Arch666Angel/mods/commit/81f0be0663f7e45b40b7fa08eb9893f3664946c5) got no errors.
